trigger:
  branches:
    include:
    - main
  paths:
    include:
    - prod/backend/**
    exclude:
    - prod/frontend/**

pool:
  name: 'Training'

variables:
  KUBE_CONFIG: '$(System.DefaultWorkingDirectory)/kubeconfig'
  K8S_CLUSTER_NAME: 'msa-aks-cluster'  
  K8S_RESOURCE_GROUP: 'tuannguyen' 

steps:
- script: |
    az aks get-credentials --resource-group $(K8S_RESOURCE_GROUP) --name $(K8S_CLUSTER_NAME) --file $(KUBE_CONFIG)
  displayName: 'Fetch kubeconfig from AKS'
- task: KubernetesManifest@0
  displayName: 'Apply Deployment and Service to AKS'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'my-aks-connection'
    manifests: |
      $(System.DefaultWorkingDirectory)/prod/backend/deployment.yaml
      $(System.DefaultWorkingDirectory)/prod/backend/service.yaml