apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-frontend-deployment
  labels:
    app: msa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-frontend
  template:
    metadata:
      labels:
        app: msa-frontend
    spec:
      containers:
      - name: msa-frontend
        image: msafrontend1.azurecr.io/frontend:v1.86
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_BACKEND_APP_API_URL
          value: http://172.188.194.242:3000
