apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-frontend-deployment
  labels:
    app: msa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-frontend
  template:
    metadata:
      labels:
        app: msa-frontend
    spec:
      containers:
      - name: msa-frontend
        image: 381492305009.dkr.ecr.ap-southeast-1.amazonaws.com/msa-frontend:v1.32-20241225134308
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_BACKEND_APP_API_URL
          value: http://a8c84db3af107406b980a8038022642c-117429841.ap-southeast-1.elb.amazonaws.com:3000