apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-frontend-deployment
  labels:
    app: msa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-frontend
  template:
    metadata:
      labels:
        app: msa-frontend
    spec:
      containers:
      - name: msa-frontend
        image: 381492305009.dkr.ecr.ap-southeast-1.amazonaws.com/msa-frontend:v1.28-20241225023250
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
