apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-frontend-deployment
  labels:
    app: msa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-frontend
  template:
    metadata:
      labels:
        app: msa-frontend
    spec:
      containers:
      - name: msa-frontend
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/msa-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
