apiVersion: v1
kind: Service
metadata:
  name: msa-frontend-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: msa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  env:
    - name: NODE_ENV
      value: "production"
    - name: BACKEND_APP_API_URL
      value: a52bd0323a69048afb939b98366450f2-944157769.ap-southeast-1.elb.amazonaws.com
