apiVersion: v1
kind: Service
metadata:
  name: msa-frontend-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: msa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000