apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-backend-deployment
  labels:
    app: msa-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-backend
  template:
    metadata:
      labels:
        app: msa-backend
    spec:
      containers:
      - name: msa-backend
        image: msabackend1.azurecr.io/backend:v1.90
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: mongodb://172.188.162.189:27017/TodoApp

