apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-backend-deployment
  labels:
    app: msa-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-backend
  template:
    metadata:
      labels:
        app: msa-backend
    spec:
      containers:
      - name: msa-backend
        image: 381492305009.dkr.ecr.ap-southeast-1.amazonaws.com/msa-backend:v1.46-20241225042541
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: mongodb://47.129.7.247:27017/TodoApp

