apiVersion: v1
kind: Service
metadata:
  name: msa-backend-service
spec:
  type: LoadBalancer
  selector:
    app: msa-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
env:
  - name: NODE_ENV
    value: "production"
  - name: MONGODB_URL
    value: mongodb://47.129.7.247:27017
